name: gravatar
version: 1.2.3
authors:
- Nik Graf <nik@blossom.io>
- Thomas Schranz <thomas@blossom.io>
description: Generate Gravatar Image Urls
homepage: https://github.com/blossom/gravatar
documentation: http://blossom.github.com/gravatar/doc/gravatar/Gravatar.html
dependencies:
  crypto: '>=0.6.5'
dev_dependencies:
  unittest: '>=0.8.1'
