name: gravatar
version: 1.2.0
authors:
- Nik Graf <nik@blossom.io>
- Thomas Schranz <thomas@blossom.io>
description: Generate Gravatar Image Urls
homepage: https://github.com/blossom/gravatar
documentation: http://blossom.github.com/gravatar/doc/gravatar/Gravatar.html
dev_dependencies:
  unittest: any
